@csrf

@php
    $unitOptions = config('pos.inventory_units', []);
    $selectedUnit = strtolower(trim((string) old('unit', $stockItem->unit)));
    $skuAutoGenerated = old('sku_auto_generated', $stockItem->sku ? '0' : '1');
@endphp

<div class="grid grid-cols-1 md:grid-cols-2 gap-4">
    <div>
        <label class="block text-sm font-semibold text-gray-700">Category</label>
        <select name="category_id" class="w-full border rounded p-2">
            @foreach ($categories as $category)
                <option value="{{ $category->id }}" @selected(old('category_id', $stockItem->category_id) == $category->id)>
                    {{ $category->name }}
                </option>
            @endforeach
        </select>
        @error('category_id') <p class="text-sm text-red-600">{{ $message }}</p> @enderror
    </div>

    <div>
        <label class="block text-sm font-semibold text-gray-700">Name</label>
        <input id="stock-name" name="name" value="{{ old('name', $stockItem->name) }}" class="w-full border rounded p-2">
        @error('name') <p class="text-sm text-red-600">{{ $message }}</p> @enderror
    </div>

    <div>
        <label class="block text-sm font-semibold text-gray-700">Default Supplier</label>
        <select name="default_supplier_id" class="w-full border rounded p-2">
            <option value="">None</option>
            @foreach ($suppliers as $supplier)
                <option value="{{ $supplier->id }}" @selected(old('default_supplier_id', $stockItem->default_supplier_id) == $supplier->id)>
                    {{ $supplier->name }}
                </option>
            @endforeach
        </select>
        @error('default_supplier_id') <p class="text-sm text-red-600">{{ $message }}</p> @enderror
    </div>

    <div>
        <label class="block text-sm font-semibold text-gray-700">Unit</label>
        <select id="stock-unit" name="unit" class="w-full border rounded p-2">
            <option value="">Select unit</option>
            @if ($selectedUnit && !array_key_exists($selectedUnit, $unitOptions))
                <option value="{{ $selectedUnit }}" selected>{{ ucfirst($selectedUnit) }}</option>
            @endif
            @foreach ($unitOptions as $value => $label)
                <option value="{{ $value }}" @selected($selectedUnit === $value)>{{ $label }}</option>
            @endforeach
        </select>
        @error('unit') <p class="text-sm text-red-600">{{ $message }}</p> @enderror
    </div>

    <div>
        <label class="block text-sm font-semibold text-gray-700">SKU</label>
        <input id="stock-sku" name="sku" value="{{ old('sku', $stockItem->sku) }}" class="w-full border rounded p-2" placeholder="Auto generated from name and unit">
        <input id="stock-sku-auto" type="hidden" name="sku_auto_generated" value="{{ $skuAutoGenerated }}">
        <p class="text-xs text-gray-500 mt-1">Leave the auto value unless you need a custom SKU.</p>
        @error('sku') <p class="text-sm text-red-600">{{ $message }}</p> @enderror
    </div>

    <div>
        <label class="block text-sm font-semibold text-gray-700">Current Quantity</label>
        <input name="current_quantity" type="number" step="0.001" value="{{ old('current_quantity', $stockItem->current_quantity) }}" class="w-full border rounded p-2">
        @error('current_quantity') <p class="text-sm text-red-600">{{ $message }}</p> @enderror
    </div>

    <div>
        <label class="block text-sm font-semibold text-gray-700">Low Stock Threshold</label>
        <input name="low_stock_threshold" type="number" step="0.001" value="{{ old('low_stock_threshold', $stockItem->low_stock_threshold) }}" class="w-full border rounded p-2">
        @error('low_stock_threshold') <p class="text-sm text-red-600">{{ $message }}</p> @enderror
    </div>

    <div>
        <label class="block text-sm font-semibold text-gray-700">Average Unit Cost</label>
        <input name="average_unit_cost" type="number" step="0.01" value="{{ old('average_unit_cost', $stockItem->average_unit_cost ?? 0) }}" class="w-full border rounded p-2">
        @error('average_unit_cost') <p class="text-sm text-red-600">{{ $message }}</p> @enderror
    </div>

    <div>
        <label class="block text-sm font-semibold text-gray-700">Last Purchase Cost</label>
        <input name="last_purchase_cost" type="number" step="0.01" value="{{ old('last_purchase_cost', $stockItem->last_purchase_cost ?? 0) }}" class="w-full border rounded p-2">
        @error('last_purchase_cost') <p class="text-sm text-red-600">{{ $message }}</p> @enderror
    </div>
</div>

<div class="flex gap-6 mt-4">
    <label class="inline-flex items-center gap-2">
        <input type="checkbox" name="auto_deduct" value="1" @checked(old('auto_deduct', $stockItem->auto_deduct))>
        <span>Auto deduct on sale</span>
    </label>
    <label class="inline-flex items-center gap-2">
        <input type="checkbox" name="active" value="1" @checked(old('active', $stockItem->active ?? true))>
        <span>Active</span>
    </label>
</div>

<div class="mt-6 flex gap-3">
    <button type="submit" class="px-4 py-2 bg-green-600 text-white rounded font-semibold">Save</button>
    <a href="{{ route('inventory.stock-items.index') }}" class="px-4 py-2 bg-gray-200 rounded font-semibold">Cancel</a>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const nameInput = document.querySelector('#stock-name');
        const unitSelect = document.querySelector('#stock-unit');
        const skuInput = document.querySelector('#stock-sku');
        const skuAutoInput = document.querySelector('#stock-sku-auto');

        if (!nameInput || !unitSelect || !skuInput || !skuAutoInput) {
            return;
        }

        function skuPart(value) {
            return (value || '')
                .toString()
                .trim()
                .toUpperCase()
                .replace(/[^A-Z0-9]+/g, '-')
                .replace(/^-+|-+$/g, '')
                .slice(0, 12);
        }

        function buildSku() {
            const namePart = skuPart(nameInput.value) || 'ITEM';
            const unitPart = skuPart(unitSelect.value) || 'UNIT';
            return `${namePart}-${unitPart}-AUTO`;
        }

        function refreshAutoSku() {
            if (skuAutoInput.value === '1') {
                skuInput.value = buildSku();
            }
        }

        skuInput.addEventListener('input', function () {
            skuAutoInput.value = skuInput.value.trim() === '' || skuInput.value.endsWith('-AUTO') ? '1' : '0';
        });

        nameInput.addEventListener('input', refreshAutoSku);
        unitSelect.addEventListener('change', refreshAutoSku);
        refreshAutoSku();
    });
</script>
